# Aider Configuration

# For comprehensive development guidelines, please refer to AGENTS.md
# AGENTS.md contains:
# - Development commands (build, test, format)
# - Architecture and design patterns
# - Code style guidelines
# - CI/CD information
# - Implementation notes
#
# This repository maintains a single source of truth in AGENTS.md
# that is shared across all AI coding assistants.

read: AGENTS.md
